// Ready translated locale messages
const langPlaceholders = {
    en: {
    message: {
        currentProj: 'Current project',
        logOut: 'Log Out',
        cscOrg: 'CSC - IT Center For Science LTD.',
        devel: 'developed by',
        table: {
            name: 'Name',
            objects: 'Objects',
            size: 'Size',
            modified: 'Last Modified',
            paginated: 'Paginated',
            pageNb: 'per page',
            fileHash: 'Hash',
            fileType: 'Type',
            fileDown: 'File Download',
        },
        dashboard: {
            prj_usage: 'Project usage',
            account: 'Account: ',
            containers: 'Containers',
            objects: 'Objects: ',
            usage: 'Usage: ',
            cur_billing: 'Currently consumes',
            prj_str_usag: 'Project storage usage: ',
            equals: 'Equals:',
            more_info: 'More information',
            billing_info: 'Pouta billing information',
            quota_info: 'Pouta default quotas',
            avail_info: 'Information on project billing unit availability etc.',
            dashboard: 'User information',
            browser: 'Browser',
        },
        largeFileMessage: '',
        download: 'Download',
        downloadLink: 'Download Link',
        downloadAlt: 'Download link for',
        downloadAltLarge: 'Confirm download large file',
        largeDownMessage: 'No large (> 1GiB) downloads enabled. \
                           Click to enable them for the duration of the session.',
        largeDownAction: 'Enable',
        emptyContainer: 'This container is empty.',
        emptyProject: 'The project doesn\'t contain any containers.',
        searchBy: 'Search by Name',
        }
    },
    fi: {
        message: {
            currentProj: 'Nykyinen projekti',
            logOut: 'Kirjaudu ulos',
            cscOrg: 'CSC – Tieteen Tietotekniikan Keskus Oy',
            devel: 'kehittänyt',
            table: {
                name: 'Nimi',
                objects: 'Objekteja',
                size: 'Koko',
                modified: 'Muokattu viimeksi',
                paginated: 'Sivutus',
                pageNb: 'sivulla',
                fileHash: 'Tarkistussumma',
                fileType: 'Tyyppi',
                fileDown: 'Tiedoston lataus',
            },
            dashboard: {
                prj_usage: 'Projektin resurssienkäyttö',
                account: 'Käyttäjä: ',
                containers: 'Kontteja: ',
                objects: 'Objekteja: ',
                usage: 'Tilankäyttö: ',
                cur_billing: 'Nykyinen kulutus',
                prj_str_usag: 'Projektin tilankäyttö: ',
                equals: 'Tarkoittaen: ',
                more_info: 'Lisätietoja',
                billing_info: 'Tietoa Pouta-palvelun laskutuksesta (englanniksi)',
                quota_info: 'Tietoa Pouta-palvelun käyttörajoista (englanniksi)',
                avail_info: 'Tietoa projektin laskutusyksiköiden määrästä jne. (englanniksi)',
                dashboard: 'Käyttäjän tiedot',
                browser: 'Selain',
            },
            largeFileMessage: '',
            download: 'Lataa',
            downloadLink: 'Latauslinkki',
            downloadAlt: 'Latauslinkki tiedostolle',
            downloadAltLarge: 'Hyväksy suuren tiedoston lataus',
            largeDownMessage: 'Suurten tiedostojen (> 1Gt) lataus täytyy hyväksyä \
                               erikseen. Paina hyväksyäksesi suuret lataukset nykyisen \
                               kirjautumisen ajaksi.',
            largeDownAction: 'Hyväksy',
            emptyContainer: 'Säiliö on tyhjä.',
            emptyProject: 'Projektilla ei ole säiliöitä.',
            searchBy: 'Etsi nimellä',
        }
    }
}

