// Ready translated locale messages

const translations = {
  en: {
    message: {
      index: {
        logIn: "Log In",
      },
      error: {
        frontPage: "To the Front Page",
        Unauthorized: "401 – Not logged in",
        Unauthorized_text: "The action requested requires logging " +
                           "in. Use the button below to Log in.",
        Notfound: "404 – Could not find the page that was requested.",
        Notfound_text: "The front page, however, can be found – in the link " +
                       "below.",
        Forbidden: "403 – Wait, that is forbidden!",
        Forbidden_text: "The previous request could not be fulfilled. " +
                        "If said operation should be allowed to be " +
                        "performed, contact the service administrator. " +
                        "Otherwise head back to the front page from the " +
                        "button below.",
      },
      program_name: "Object Browser",
      currentProj: "Current project",
      logOut: "Log Out",
      cscOrg: "CSC - IT Center For Science LTD",
      devel: "developed by",
      table: {
        name: "Name",
        objects: "Objects",
        size: "Size",
        modified: "Last Modified",
        paginated: "Paginated",
        pageNb: "per page",
        fileHash: "Hash",
        fileType: "Type",
        fileDown: "File Download",
        owner: "Container owner",
        created: "Created",
        folderDetails: "No details for folders",
      },
      discover: {
        sync_shares: "Synchronize shared containers",
        sync_success_template: "Successfully synchronized ",
        sync_success_concat: " shared containers",
        sync_failure_template: "No new shared containers to synchronize.",
      },
      dashboard: {
        prj_usage: "Project usage",
        account: "Account",
        containers: "Containers",
        objects: "Objects",
        usage: "Usage",
        cur_billing: "Currently consumes",
        prj_str_usag: "Project storage usage",
        equals: "Equals",
        more_info: "More information",
        billing_info: "Pouta billing information",
        quota_info: "Pouta default quotas",
        avail_info: "Information on project billing unit availability etc.",
        dashboard: "User information",
        browser: "Browser",
        tooltip_disable: "Hide tooltip",
        hour: "hour",
        default_notify: "The information on consumed billing units and the " +
                        "available quota is derived from the default Pouta " +
                        "values. If there's a separate pricing contract " +
                        "with CSC for the project used, the values " +
                        "specific the project may vary.",
        pouta_accounting: "https://docs.csc.fi/cloud/pouta/accounting/",
        pouta_obj_store_quota_info: "https://docs.csc.fi/data/Allas/introduction/#billing-and-quotas",
        my_csc: "https://my.csc.fi",
        resources: "Resources",
        tokens: "Tokens",
      },
      share: {
        share: "Share",
        share_cont: "Share the container",
        read_perm: "Grant read permissions",
        write_perm: "Grant write permissions",
        field_label: "UUIDs to share with",
        field_placeholder: "Add UUIDs here",
        cancel: "Cancel",
        confirm: "Share",
        to_me: "Shared to the project",
        from_me: "Shared from the project",
        request_sharing: "Request sharing",
        shared: "Shared",
        container: "Container",
        owner: "Container owner",
        shared_details_to: "Shared to: ",
        shared_details_address: "Container address: ",
        shared_details_rights: "Rights given: ",
        shared_details_read: "Read access",
        shared_details_write: "Write access",
        created: "Created",
        fail_noperm: "Please select permissions to grant!",
        fail_noid: "Please give at least one project ID!",
        fail_nocont: "Please specify the container!",
        fail_duplicate: "The project already has access to the container!",
        new_share_button: "Share a container",
        container_label: "Container",
        revoke: "Revoke container access",
        revoke_project: "Revoke access from project",
        success_delete: "Successfully deleted sharing action",
        request_sync_nocont: "Cannot synchronize access requests without a " +
                             "container",
        request_synced: "Successfully synchronized access requests",
        request_not_synced: "No access requests to sync",
        sync_requests: "Synchronize container share requests",
      },
      request: {
        project: "Project",
        container: "Container / Identfier",
        container_message: "The requested container name",
        owner: "Owner",
        owner_message: "The requested container owner",
        request: "Request",
        multi_project: "Account has access to multiple projects. " +
                       "Please verify that the correct project is set " +
                       "active in the menu, and submit the request with " +
                       "the Request button.",
      },
      largeFileMessage: "",
      download: " Download",
      downloadLink: "Download Link",
      downloadContainer: " Download Container",
      downloadAlt: "Download link for",
      downloadAltLarge: "Confirm download large file",
      largeDownMessage: "No large (> 1GiB) downloads enabled. Click to " +
                        "enable them for the duration of the session.",
      largeDownAction: "Enable",
      emptyContainer: "This container is empty.",
      emptyProject: "The project does not contain any containers.",
      emptyShared: "No containers have been shared to the project.",
      emptyRequested: "No shared containers have been requested for the " +
                      "project.",
      searchBy: "Search by Name",
      sharing: "Sharing - ",
      containers: "Containers - ",
      upload: " Upload",
      uploadfolder: " Upload Folder",
      chunking: "Chunking",
      uploading: "Uploading ",
      cancelupload: " Cancel uploading",
      addfiles: "File / Files scheduled for uploading",
      upfinish: "Finished uploading ",
      upfail: "Failed uploading ",
      upnotsupported: "Uploading is not supported on your browser",
      copy: " Copy",
      copysuccess: "Started copying the container in the background",
      copyfail: "Failed to copy the container",
      renderFolders: "Render as Folders",
      replicate: {
        destinationLabel: "Destination container",
        destinationMessage: "Insert copy destination container here",
        destinationExists: " Destination already exists",
      },
      tokens: {
        empty: "No API tokens created for the project",
        identifier: "Identifier",
        revoke: "Revoke",
        identLabel: "New token identifier",
        identMessage: "Insert new token identifier here",
        createToken: "Create token",
        latestToken: "Latest token: ",
        copyToken: "The token will be displayed just this once after its " +
                   "creation, and recovering it will not be possible " +
                   "afterwards. Please make sure that you have stored " +
                   "the token somewhere before navigating away from the " +
                   "token page.",
        tokenCopied: "Token copied.",
      },
    },
  },
  fi: {
    message: {
      index: {
        logIn: "Kirjaudu sisään",
      },
      error: {
        frontPage: "Etusivulle",
        Unauthorized: "401 – Kirjaudu sisään",
        Unauthorized_text: "Sivun näyttäminen vaatii sisäänkirjauksen, " +
                           "jonka voi toteuttaa oheisesta painikkeesta.",
        Notfound: "404 – Etsittyä sivua ei löydetty.",
        Notfound_text: "Etusivun voi löytää alapuolisesta painikkeesta.",
        Forbidden: "403 – Tuo on kiellettyä.",
        Forbidden_text: "Edellinen operaatio ei ole sallittu. Mikäli " +
                        "kyseisen operaation tulisi olla sallittu, ota " +
                        "yhteys palvelun ylläpitoon. Muussa tapauksessa " +
                        "paluu etusivulle on mahdollista oheisesta " +
                        "painikkeesta",
      },
      program_name: "Object Browser",
      currentProj: "Nykyinen projekti",
      logOut: "Kirjaudu ulos",
      cscOrg: "CSC – Tieteen Tietotekniikan Keskus Oy",
      devel: "kehittänyt",
      table: {
        name: "Nimi",
        objects: "Objekteja",
        size: "Koko",
        modified: "Muokattu viimeksi",
        paginated: "Sivutus",
        pageNb: "sivulla",
        fileHash: "Tarkistussumma",
        fileType: "Tyyppi",
        fileDown: "Tiedoston lataus",
        owner: "Säiliön omistaja",
        created: "Luotu",
        folderDetails: "Ei yksityiskohtia kansioille",
      },
      discover: {
        sync_shares: "Synkronoi jaetut säiliöt",
        sync_success_template: "Synkronoitiin ",
        sync_success_concat: " jaettua säiliötä",
        sync_failure_template: "Ei uusia jaettuja säiliöitä synkronoitavaksi.",
      },
      dashboard: {
        prj_usage: "Projektin resurssienkäyttö",
        account: "Käyttäjä",
        containers: "Kontteja",
        objects: "Objekteja",
        usage: "Tilankäyttö",
        cur_billing: "Nykyinen kulutus",
        prj_str_usag: "Projektin tilankäyttö",
        equals: "Tarkoittaen",
        more_info: "Lisätietoja",
        billing_info: "Tietoa Pouta-palvelun laskutuksesta (englanniksi)",
        quota_info: "Tietoa Pouta-palvelun käyttörajoista (englanniksi)",
        avail_info: "Tietoa projektin laskutusyksiköiden määrästä jne. " +
                    "(englanniksi)",
        dashboard: "Käyttäjän tiedot",
        browser: "Selain",
        tooltip_disable: "Piilota ohje",
        hour: "tunti",
        default_notify: "Esitetty tieto laskutusysiköiden kulutuksesta ja " +
                        "käyttörajoista on laskettu Poudan oletusarvojen " +
                        "mukaan. Jos käytetylle projektille on erillinen " +
                        "sopimus laskutuksesta CSC:n kanssa, tarkat arvot " +
                        "voivat poiketa näytetyistä.",
        pouta_accounting: "https://docs.csc.fi/cloud/pouta/accounting/",
        pouta_obj_store_quota_info: "https://docs.csc.fi/data/Allas/introduction/#billing-and-quotas",
        my_csc: "https://my.csc.fi",
        resources: "Resurssit",
        tokens: "Avaimet",
      },
      share: {
        share: "Jaa",
        share_cont: "Jaa säiliö",
        read_perm: "Salli säiliön luku",
        write_perm: "Salli säiliöön kirjoitus",
        field_label: "Jaa UUID:lle",
        field_placeholder: "Lisää UUID:t",
        cancel: "Peru",
        confirm: "Jaa",
        to_me: "Jaettu projektille",
        from_me: "Jaettu projektista",
        request_sharing: "Pyydä jakamista",
        shared: "Jaettu",
        container: "Säiliö",
        owner: "Säiliön omistaja",
        created: "Luotu",
        shared_details_to: "Jaettu projektille: ",
        shared_details_address: "Säiliön osoite: ",
        shared_details_rights: "Annetut oikeudet: ",
        shared_details_read: "Lukuoikeus",
        shared_details_write: "Kirjoitusoikeus",
        fail_noperm: "Valitse jaettavat oikeudet!",
        fail_noid: "Anna vähintään yhden projektin tunnus (Project ID)!",
        fail_nocont: "Anna jaettava säiliö!",
        fail_duplicate: "Säiliö on jo jaettu projektille!",
        new_share_button: "Jaa säiliö",
        container_label: "Säiliö",
        revoke: "Poista jakaminen",
        revoke_project: "Poista jakaminen projektilta",
        success_delete: "Säiliön jaetun oikeuden poistaminen onnistui",
        request_sync_nocont: "Ei voida hakea jakopyyntöjä ilman säiliötä",
        request_synced: "Säiliön jakopyyntöjen haku onnistui",
        request_not_synced: "Ei säiliötä koskevia jakopyyntöjä",
        sync_requests: "Synkronoi säiliön jakopyynnöt",
      },
      request: {
        project: "Projekti",
        container: "Säiliö / tunniste",
        container_message: "Jaettavaksi pyydetyn säiliön nimi",
        owner: "Omistaja",
        owner_message: "Jaettavaksi pyydetyn säiliön omistaja",
        request: "Pyydä jakoa",
        multi_project: "Käyttäjällä on pääsy useisiin projekteihin. " +
                       "Tarkistathan, että haluttu projekti on valittu " +
                       "valikossa, ja lisää pyyntö Pyydä jakoa " +
                       "-painikkeella.",
      },
      largeFileMessage: "",
      download: " Lataa",
      downloadContainer: " Lataa säiliö",
      downloadLink: "Latauslinkki",
      downloadAlt: "Latauslinkki tiedostolle",
      downloadAltLarge: "Hyväksy suuren tiedoston lataus",
      largeDownMessage: "Suurten tiedostojen (> 1Gt) lataus täytyy hyväksyä " +
                        "erikseen. Paina hyväksyäksesi suuret lataukset " +
                        "nykyisen kirjautumisen ajaksi.",
      largeDownAction: "Hyväksy",
      emptyContainer: "Säiliö on tyhjä.",
      emptyProject: "Projektilla ei ole säiliöitä.",
      emptyShared: "Projektille ei ole jaettu säiliöitä.",
      emptyRequested: "Projektille ei ole pyydetty jakamaan säiliöitä.",
      searchBy: "Etsi nimellä",
      sharing: "Jako - ",
      containers: "Säiliöt - ",
      upload: " Lähetä",
      uploadfolder: " Lähetä kansio",
      chunking: "Paloitellaan ",
      uploading: "Lähetetään ",
      cancelupload: " Peru lähetys",
      addfiles: "Lisättiin tiedosto / tiedostoja lähetettäväksi",
      upfinish: "Lähetettiin tiedosto ",
      upfail: "Epäonnistuttiin lähettäessä tiedosto ",
      upnotsupported: "Selain ei tue tiedostojen lähettämistä",
      copy: " Kopioi",
      copysuccess: "Aloitettiin säiliön kopiointi taustalla",
      copyfail: "Säiliön kopiointi epäonnistui",
      renderFolders: "Näytä kansioina",
      replicate: {
        destinationLabel: "Kohdesäiliö",
        destinationMessage: "Lisää kopioinnin kohdesäiliö tähän",
        destinationExists: " Kohdesäililö on jo olemassa",
      },
      tokens: {
        empty: "Projektille ei ole luotu API-avaimia",
        identifier: "Tunniste",
        revoke: "Mitätöi",
        identLabel: "Uuden avaimen tunniste",
        identMessage: "Syötä tunniste uudelle API-avaimelle",
        createToken: "Luo avain",
        latestToken: "Viimeisin avain: ",
        copyToken: "Avain näytetään vain kerran luonnin jälkeen, eikä sen " +
                   "kopiointi tai palautus jälkeenpäin ole mahdollista. " +
                   "Varmistathan ottaneesi avaimen talteen ennen " +
                   "navigointia pois sivulta.",
        tokenCopied: "Avain kopioitu.",
      },
    },
  },
};

export default translations;
