FROM debian:latest

RUN apt-get update && apt-get -y upgrade
RUN apt-get -y install firefox-esr ca-certificates xinit openssh-server
RUN mkdir -p /root/.ssh

ADD .devres/ca/devCA.crt /usr/local/share/ca-certificates/devCA.crt
ADD .devres/ssh/ff-dev.pub /root/.ssh/authorized_keys

RUN update-ca-certificates
RUN mkdir -p /run/sshd

EXPOSE 22
CMD ["/sbin/sshd", "-D"]
