FROM debian:latest

RUN apt-get update && apt-get -y upgrade
RUN apt-get -y install chromium ca-certificates xinit openssh-server libnss3-tools
RUN mkdir -p /root/.ssh

ADD ./.devres/ca/sd-connect.devca.crt /usr/local/share/ca-certificates/sd-connect.devca.crt
ADD ./.devres/ca/sd-connect.devca.crt /usr/share/ca-certificates/mozilla/sd-connect.devca.crt
ADD ./.devres/ssh/chrome-dev.pub /root/.ssh/authorized_keys

RUN update-ca-certificates
RUN mkdir -p /run/sshd

# sleep is necessary so chromium has time to fail and exit -> required to initialize browser configuration
RUN (chromium --headless --no-sandbox &); sleep 5
# Install the root CA to Chrome DB
RUN certutil -d sql:/root/.pki/nssdb -A -t "TCu" -n "sd-connect.devenv CA" -i /usr/local/share/ca-certificates/sd-connect.devca.crt

EXPOSE 22
CMD ["/sbin/sshd", "-D"]
