FROM python:3.12-bookworm

COPY . /tmpsrc

RUN cd tmpsrc && pip install --break-system-packages . && pip install --break-system-packages .[dev] && cd / && rm -rf tmpsrc

RUN apt-get -y update && apt-get -y upgrade && apt-get -y install
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
RUN bash -l -c "nvm install 22 && npm install --global corepack@latest && corepack enable npm"
RUN echo "PATH=/emsdk:/emsdk/upstream/emscripten:/emsdk/node/18.20.3_64bit/bin:${PATH}" > /etc/environment

COPY --from=ghcr.io/cscfi/docker-emscripten-crypt4gh /emsdk /emsdk

VOLUME [ "/src" ]
WORKDIR /src

CMD [ "bash", "-l", "-c", "honcho start" ]
