FROM python:3.10-alpine3.17 as BACKEND

COPY pyproject.toml /root/swift_upload_runner/pyproject.toml
COPY README.md /root/swift_upload_runner/README.md
COPY swift_browser_ui /root/swift_upload_runner/swift_browser_ui

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade pip \
    && pip install /root/swift_upload_runner

FROM python:3.10-alpine3.17

LABEL maintainer "CSC Developers"
LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.vcs-url="https://github.com/CSCFI/swift-upload-runner"

COPY --from=BACKEND /usr/local/lib/python3.10 /usr/local/lib/python3.10/

COPY --from=BACKEND /usr/local/bin/gunicorn /usr/local/bin/

COPY --from=BACKEND /usr/local/bin/swift-upload-runner /usr/local/bin

RUN mkdir -p /app

WORKDIR /app

COPY ./deploy/app-runner.sh /app/app.sh

RUN chmod +x /app/app.sh

RUN adduser --disabled-password --no-create-home swiftrunner
USER swiftrunner

ENTRYPOINT ["/bin/sh", "-c", "/app/app.sh"]
