# Build libsodium
FROM emscripten/emsdk:latest AS SODIUM

ENV LIBSODIUM_VERSION 1.0.18-stable

ADD https://download.libsodium.org/libsodium/releases/libsodium-${LIBSODIUM_VERSION}.tar.gz .

RUN tar xvf libsodium-${LIBSODIUM_VERSION}.tar.gz \
    && cd libsodium-stable \
    && dist-build/emscripten.sh --sumo

# Build openssl
FROM emscripten/emsdk:latest AS OPENSSL

ENV OPENSSL_VERSION 1.1.1s

ADD https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz .
ADD https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz.sha256 .

RUN bash -c 'if [[ $(sha256sum < openssl-${OPENSSL_VERSION}.tar.gz) != *$(cat openssl-${OPENSSL_VERSION}.tar.gz.sha256)* ]]; then echo $(sha256sum < openssl-${OPENSSL_VERSION}.tar.gz) $(curl https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz.sha256); echo Downloaded file checksum does not match. ; exit 1; fi' \
    && tar xvf openssl-${OPENSSL_VERSION}.tar.gz \
    && cd openssl-${OPENSSL_VERSION} \
    && emconfigure ./Configure linux-generic64 no-asm no-threads no-engine no-hw no-weak-ssl-ciphers no-dtls no-shared no-dso --prefix=/emsdk/upstream \
    && sed -i 's|^CROSS_COMPILE.*$|CROSS_COMPILE=|g' Makefile \
    && sed -i '/^CFLAGS/ s/$/ -D__STDC_NO_ATOMICS__=1/' Makefile \
    && sed -i '/^CXXFLAGS/ s/$/ -D__STDC_NO_ATOMICS__=1/' Makefile \
    && emmake make -j 2 all \
    && emmake make install

# Build libcrypt4gh
FROM emscripten/emsdk:latest AS LIBCRYPT4GH

RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache

RUN --mount=type=cache,target=/var/cache/apt --mount=type=cache,target=/var/lib/apt \
    apt-get update -q \
    && apt-get upgrade -yq -o Dpkg::Options::="--force-confold" \
    && apt-get install -yq autoconf

COPY --from=SODIUM /src/libsodium-stable/libsodium-js-sumo/include/ /emsdk/upstream/include/
COPY --from=SODIUM /src/libsodium-stable/libsodium-js-sumo/lib/ /emsdk/upstream/lib/

ADD https://api.github.com/repos/cscfi/libcrypt4gh/compare/main...HEAD /dev/null
RUN git clone --single-branch https://github.com/CSCfi/libcrypt4gh

# We'll skip linking libraries since emcc only produces static libraries
# Linking sodium at this point causes a linker conflict – thus cutting out $(LIBS)
RUN  export EMCC_CFLAGS="-I/emsdk/upstream/include -L/emsdk/upstream/lib" \
    && export LDFLAGS="-L/emsdk/upstream/lib" \
    && cd libcrypt4gh \
    && autoreconf --install \
    && sed -i 's/$(LIBS) //' Makefile.in \
    && emconfigure ./configure --prefix=/emsdk/upstream \
    && emmake make \
    && emmake make install

# Build libcrypt4gh-keys
FROM emscripten/emsdk:latest AS LIBCRYPT4GHKEYS

COPY --from=SODIUM /src/libsodium-stable/libsodium-js-sumo/include/ /emsdk/upstream/include/
COPY --from=SODIUM /src/libsodium-stable/libsodium-js-sumo/lib/ /emsdk/upstream/lib/

COPY --from=OPENSSL /emsdk/upstream/include/ /emsdk/upstream/include/
COPY --from=OPENSSL /emsdk/upstream/lib/ /emsdk/upstream/lib/

RUN --mount=type=cache,target=/var/cache/apt --mount=type=cache,target=/var/lib/apt \
    apt-get update -q \
    && apt-get upgrade -yq -o Dpkg::Options::="--force-confold" \
    && apt-get install -yq autoconf build-essential

ADD https://api.github.com/repos/cscfi/libcrypt4gh-keys/compare/main...HEAD /dev/null
RUN git clone --single-branch https://github.com/CSCfi/libcrypt4gh-keys.git

# We'll skip linking libraries since emcc only produces static libraries
# Linking sodium at this point causes a linker conflict – thus cutting out $(LIBS)
RUN export EMCC_CFLAGS="-I/emsdk/upstream/include -L/emsdk/upstream/lib" \
    && export LDFLAGS="-L/emsdk/upstream/lib" \
    && cd libcrypt4gh-keys \
    && autoreconf --install \
    && sed -i 's/$(LIBS) //' Makefile.in \
    && emconfigure ./configure --prefix=/emsdk/upstream --with-openssl=/emsdk/upstream \
    && emmake make \
    && emmake make install

# Build wasm encryption
FROM emscripten/emsdk:latest AS WASMCRYPT

COPY --from=SODIUM /src/libsodium-stable/libsodium-js-sumo/include/ /emsdk/upstream/include/
COPY --from=SODIUM /src/libsodium-stable/libsodium-js-sumo/lib/ /emsdk/upstream/lib/

COPY --from=LIBCRYPT4GH /emsdk/upstream/include/ /emsdk/upstream/include/
COPY --from=LIBCRYPT4GH /emsdk/upstream/lib/ /emsdk/upstream/lib/

COPY --from=LIBCRYPT4GHKEYS /emsdk/upstream/include/ /emsdk/upstream/include/
COPY --from=LIBCRYPT4GHKEYS /emsdk/upstream/lib/ /emsdk/upstream/lib/

COPY swift_browser_ui_frontend/wasm/ /src/

RUN export EMCC_CFLAGS="-I/emsdk/upstream/include -L/emsdk/upstream/lib" \
    && export EMCC_FORCE_STDLIBS=libc \
    && emmake make

# Build UI with encryption
FROM node:18-alpine3.17 as FRONTEND

ARG OIDC_ENABLED

RUN --mount=type=cache,target=/var/cache/apk/ \
    apk add git

COPY swift_browser_ui_frontend/package.json /root/swift_ui/swift_browser_ui_frontend/package.json
COPY swift_browser_ui_frontend/package-lock.json /root/swift_ui/swift_browser_ui_frontend/package-lock.json

RUN --mount=type=cache,target=/root/.npm \
    cd /root/swift_ui/swift_browser_ui_frontend \
    && npm install

COPY . /root/swift_ui/

RUN cd /root/swift_ui/swift_browser_ui_frontend \
    && OIDC_ENABLED=$OIDC_ENABLED npm run build-devel

FROM python:3.10-alpine3.17 as BACKEND

COPY setup.py /root/swift_ui/setup.py
COPY swift_browser_ui /root/swift_ui/swift_browser_ui
COPY --from=FRONTEND /root/swift_ui/swift_browser_ui_frontend/dist /root/swift_ui/swift_browser_ui_frontend/dist
COPY --from=WASMCRYPT /src/src/libupload.js /root/swift_ui/swift_browser_ui_frontend/dist/libupload.js
COPY --from=WASMCRYPT /src/src/libupload.wasm /root/swift_ui/swift_browser_ui_frontend/dist/libupload.wasm

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade pip \
    && pip install /root/swift_ui

FROM python:3.10-alpine3.17

LABEL maintainer="CSC Developers"
LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.vcs-url="https://github.com/CSCfi/swift-browser-ui"

COPY --from=BACKEND /usr/local/lib/python3.10/ /usr/local/lib/python3.10/

COPY --from=BACKEND /usr/local/bin/gunicorn /usr/local/bin/

COPY --from=BACKEND /usr/local/bin/swift-browser-ui /usr/local/bin/

RUN mkdir -p /app

WORKDIR /app

COPY ./deploy/app.sh /app/app.sh

RUN chmod +x /app/app.sh

RUN adduser --disabled-password --no-create-home swiftui && \
    chown -R swiftui:swiftui /app
USER swiftui

ENTRYPOINT ["/bin/sh", "-c", "/app/app.sh"]
