FROM docker.io/python:3.12-alpine3.17 as BACKEND

COPY pyproject.toml /root/swift_request/pyproject.toml
COPY README.md /root/swift_request/README.md
COPY swift_browser_ui /root/swift_request/swift_browser_ui

# remove this link as it creates issues with hatch
# in pyproject.toml
RUN rm /root/swift_request/swift_browser_ui/ui/static

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade pip \
    && pip install /root/swift_request

FROM docker.io/python:3.12-alpine3.17

LABEL maintainer "CSC Developers"
LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.vcs-url="https://github.com/CSCFI/swift-sharing-request"

COPY --from=BACKEND /usr/local/lib/python3.11 /usr/local/lib/python3.11/

COPY --from=BACKEND /usr/local/bin/gunicorn /usr/local/bin/

COPY --from=BACKEND /usr/local/bin/swift-sharing-request /usr/local/bin

RUN mkdir -p /app

WORKDIR /app

COPY ./deploy/app-request.sh /app/app.sh

RUN chmod +x /app/app.sh

RUN addgroup -g 1001 swiftrequest && \
    adduser -D -u 1001 --disabled-password --no-create-home -G swiftrequest swiftrequest

USER swiftrequest

ENTRYPOINT ["/bin/sh", "-c", "/app/app.sh"]
