# Build wasm encryption
FROM ghcr.io/cscfi/docker-emscripten-crypt4gh:1.1.0 AS WASMCRYPT

COPY swift_browser_ui_frontend/wasm/ /src/

RUN bash /bin/build_wasm.sh all

# Build UI with encryption
FROM node:18-alpine3.17 as FRONTEND

ARG OIDC_ENABLED

RUN --mount=type=cache,target=/var/cache/apk/ \
    apk add git

COPY swift_browser_ui_frontend/package.json /root/swift_ui/swift_browser_ui_frontend/package.json
COPY swift_browser_ui_frontend/pnpm-lock.yaml /root/swift_ui/swift_browser_ui_frontend/pnpm-lock.yaml

RUN --mount=type=cache,target=/root/.pnpm-store \
    cd /root/swift_ui/swift_browser_ui_frontend \
    && npm install -g pnpm@7 \
    && pnpm install

COPY . /root/swift_ui/

RUN cd /root/swift_ui/swift_browser_ui_frontend \
    && OIDC_ENABLED=$OIDC_ENABLED pnpm run build-devel

FROM python:3.10-alpine3.17 as BACKEND

COPY setup.py /root/swift_ui/setup.py
COPY swift_browser_ui /root/swift_ui/swift_browser_ui
COPY --from=FRONTEND /root/swift_ui/swift_browser_ui_frontend/dist /root/swift_ui/swift_browser_ui_frontend/dist
COPY --from=WASMCRYPT /src/src/libupload.js /root/swift_ui/swift_browser_ui_frontend/dist/libupload.js
COPY --from=WASMCRYPT /src/src/libupload.wasm /root/swift_ui/swift_browser_ui_frontend/dist/libupload.wasm

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade pip \
    && pip install /root/swift_ui

FROM python:3.10-alpine3.17

LABEL maintainer="CSC Developers"
LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.vcs-url="https://github.com/CSCfi/swift-browser-ui"

COPY --from=BACKEND /usr/local/lib/python3.10/ /usr/local/lib/python3.10/

COPY --from=BACKEND /usr/local/bin/gunicorn /usr/local/bin/

COPY --from=BACKEND /usr/local/bin/swift-browser-ui /usr/local/bin/

RUN mkdir -p /app

WORKDIR /app

COPY ./deploy/app.sh /app/app.sh

RUN chmod +x /app/app.sh

RUN adduser --disabled-password --no-create-home swiftui && \
    chown -R swiftui:swiftui /app
USER swiftui

ENTRYPOINT ["/bin/sh", "-c", "/app/app.sh"]
