FROM docker.io/node:18-alpine3.17 as FRONTEND

ARG OIDC_ENABLED

RUN --mount=type=cache,target=/var/cache/apk/ \
    apk add git

COPY swift_browser_ui_frontend/package.json /root/swift_ui/swift_browser_ui_frontend/package.json
COPY swift_browser_ui_frontend/pnpm-lock.yaml /root/swift_ui/swift_browser_ui_frontend/pnpm-lock.yaml

RUN --mount=type=cache,target=/root/.pnpm-store \
    cd /root/swift_ui/swift_browser_ui_frontend \
    && npm install -g pnpm@8 \
    && pnpm install --prod

COPY swift_browser_ui_frontend /root/swift_ui/swift_browser_ui_frontend

RUN cd /root/swift_ui/swift_browser_ui_frontend \
    && OIDC_ENABLED=$OIDC_ENABLED pnpm run build-devel

FROM docker.io/python:3.11-alpine3.17 as BACKEND

COPY pyproject.toml /root/swift_ui/pyproject.toml
COPY README.md /root/swift_ui/README.md
COPY swift_browser_ui /root/swift_ui/swift_browser_ui
COPY --from=FRONTEND /root/swift_ui/swift_browser_ui_frontend/dist /root/swift_ui/swift_browser_ui_frontend/dist

RUN pip install --upgrade pip && \
    pip install /root/swift_ui

FROM docker.io/python:3.11-alpine3.17

LABEL maintainer="CSC Developers"
LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.vcs-url="https://github.com/CSCfi/swift-browser-ui"

COPY --from=BACKEND /usr/local/lib/python3.11/ /usr/local/lib/python3.11/

COPY --from=BACKEND /usr/local/bin/gunicorn /usr/local/bin/

COPY --from=BACKEND /usr/local/bin/swift-browser-ui /usr/local/bin/

RUN mkdir -p /app

WORKDIR /app

COPY ./deploy/app.sh /app/app.sh

RUN chmod +x /app/app.sh

RUN adduser --disabled-password --no-create-home swiftui && \
    chown -R swiftui:swiftui /app
USER swiftui

ENTRYPOINT ["/bin/sh", "-c", "/app/app.sh"]
