FROM python:3.10-alpine3.17 as BACKEND

COPY setup.py /root/swift_sharing/setup.py
COPY swift_browser_ui /root/swift_sharing/swift_browser_ui

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install --upgrade pip \
    && pip install /root/swift_sharing

FROM python:3.10-alpine3.17

LABEL maintainer "CSC Developers"
LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.vcs-url="https://github.com/CSCFI/swift-x-account-sharing"

COPY --from=BACKEND /usr/local/lib/python3.10 /usr/local/lib/python3.10/

COPY --from=BACKEND /usr/local/bin/gunicorn /usr/local/bin/

COPY --from=BACKEND /usr/local/bin/swift-x-account-sharing /usr/local/bin

RUN mkdir -p /app

WORKDIR /app

COPY ./deploy/app-sharing.sh /app/app.sh

RUN chmod +x /app/app.sh

RUN addgroup -g 1001 swiftsharing && \
    adduser -D -u 1001 --disabled-password --no-create-home -G swiftsharing swiftsharing

USER swiftsharing

ENTRYPOINT ["/bin/sh", "-c", "/app/app.sh"]
