openapi: "3.0.2"
info:
  title: "swift-sharing-request"
  description: "Database and API for storing / querying Openstack Swift ACL share action request information."
  version: "0.1.0"
  license:
    name: MIT
tags:
  - name: API Endpoints
    description: Endpoints for sharing request "Database and API for storing / querying Openstack Swift ACL share action request information."
paths:
  /request/user/{user}/{container}:
    post:
      tags:
        - API Endpoints
      summary: Publish a new request for access to a container
      parameters:
      - name: user
        in: path
        description: The user that's requesting access
        required: true
        schema:
          type: string
          example: AUTH_example
      - name: container
        in: path
        description: The container that the access is requested to
        required: true
        schema:
          type: string
          example: test-container
      - name: owner
        in: query
        description: The container owner that the access is requested from.
        schema:
          type: string
          example: AUTH_example
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewRequest"
    delete:
      tags:
        - API Endpoints
      summary: Delete an existing request for access
      parameters:
      - name: user
        in: path
        description: The user that originally requested access
        required: true
        schema:
          type: string
          example: AUTH_example
      - name: container
        in: path
        description: The container that the access was requested to
        required: true
        schema:
          type: string
          example: test-container
      - name: owner
        in: query
        description: The container owner that the access was requeted from.
        schema:
          type: string
          example: AUTH_example
      responses:
        200:
          description: OK
          content:
            text/plain:
                schema:
                  type: string
                  example: OK
  /request/user/{user}:
    get:
      tags:
        - API Endpoints
      summary: List container share requests made by a user.
      parameters:
      - name: user
        in: path
        description: The user querying
        required: true
        schema:
          type: string
          example: AUTH_example
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Requests"
  /request/owner/{user}:
    get:
      tags:
        - API Endpoints
      summary: List the requests owned by the user (made for the user).
      parameters:
      - name: user
        in: path
        description: The user querying
        required: true
        schema:
          type: string
          example: AUTH_example
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Requests"
  /request/container/{container}:
    get:
      tags:
        - API Endpoints
      summary: List share requests made for a container.
      parameters:
      - name: container
        in: path
        description: The container queried for
        required: true
        schema:
          type: string
          example: test-container
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContainerRequests"

components:
  schemas:

    NewRequest:
      type: object
      properties:
        user:
          type: string
          description: The user requesting access
          example: AUTH_example
        container:
          type: string
          description: The container the access is requested for
          example: test-container
        owner:
          type: string
          description: The owner that the access is requested from
          example: AUTH_example
        date:
          type: string
          description: The date the request was posted
          example: "2012-04-23T18:25:43.511Z"

    ListedRequest:
      type: object
      properties:
        user:
          type: string
          description: The user requesting access
          example: AUTH_example
        container:
          type: string
          description: The container the access is requested for
          example: test-container
        owner:
          type: string
          description: The owner that the access is requested from
          example: AUTH_example
        date:
          type: string
          description: The date the request was posted
          example: "2012-04-23T18:25:43.511Z"

    Requests:
      type: array
      items:
        $ref: "#/components/schemas/ListedRequest"

    ContainerRequests:
      type: array
      items:
        $ref: "#/components/schemas/ListedRequest"
