name: End-to-end tests
on:
  pull_request:

jobs:
  cypress-e2e-headless:
    name: Cypress e2e
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18"]
        browser: ["firefox", "chrome"]

    # https://docs.github.com/en/actions/using-containerized-services/about-service-containers
    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        volumes:
          - ${{ github.workspace }}/.github/config/init-project-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      keystone-swift:
        image: ghcr.io/cscfi/docker-keystone-swift:main
        ports:
          - 5000:5000
          - 8080:8080
        options: >-
          --name keystone-swift
          --init
    steps:
      - name: fix-permissions
        run: sudo chown -R $USER:$USER ${{ github.workspace }}
      - uses: actions/checkout@v4
      - name: Populate swift
        run: |
          docker exec keystone-swift generate_data.py --keystone --username swift --password veryfast --containers 15
          docker exec keystone-swift generate_data.py --keystone --username swift --password veryfast --project "swift-project"
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
          cache-dependency-path: swift_browser_ui_frontend/pnpm-lock.yaml
      - name: Build Frontend
        run: |
          pushd swift_browser_ui_frontend
          pnpm install
          pnpm run build-docker
      - name: Setup and Run backend
        run: |
          pip install -r requirements.txt
          pip install honcho
          honcho start -f ${{ github.workspace }}/.github/config/Procfile --env ${{ github.workspace }}/.github/config/.env.test &
      - uses: cypress-io/github-action@v5
        with:
          project: ./swift_browser_ui_frontend
          install: false
          browser: ${{ matrix.browser }}
          env: port=8000
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: swift_browser_ui_frontend/cypress/screenshots
          retention-days: 5
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: swift_browser_ui_frontend/cypress/videos
          retention-days: 5
