name: End-to-end tests
on: [push]

jobs:
  cypress-e2e-headless:
    name: Cypress e2e
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16"]
        browser: ["chrome"]
        # browser: ["firefox", "chrome"]
    
    # https://docs.github.com/en/actions/using-containerized-services/about-service-containers
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_PASSWORD: pass
        ports:
          - 5432:5432
        volumes:
          - ${{ github.workspace }}/init-project-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      keystone-swift:
        image: ghcr.io/cscfi/keystone-swift:latest
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
        ports:
          - 5000:5000
          - 8080:8080
    steps:
      - uses: actions/checkout@v2
      - name: Build Frontend
        run: |
          pushd swift_browser_ui_frontend
          npm install
          npm run build
      # - name: Start keystone-swift backend
      #   run: |
      #     docker run --init -d -p 5000:5000 -p 8080:8080 --name keystone-swift ghcr.io/cscfi/keystone-swift
      - name: Setup and Run backend
        run: |
          pip install -r requirements.txt
          pip install honcho
          honcho start -f Procfile-test --env .env.test &
      - name: Populate swift
        run: |
          pip install requests python-lorem
          python3 generate-data.py --keystone --username swift --password veryfast
      - run: npm i cypress
      - uses: cypress-io/github-action@v2
        with:
          install: false
          browser: ${{ matrix.browser }}
          headless: true
          env: port=8000
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 5
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 5
