name: Javascript ESLint check

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14']
    name: Node ${{ matrix.node }} eslint check
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: |
          pushd swift_browser_ui_frontend
          npm install -g npm@8.4.0
          npm install
          npm ci
      - name: Run eslint
        run: |
          pushd swift_browser_ui_frontend
          npm run lint
      