name: Firefox UI check

on: [pull_request]

jobs:
  ui_test:
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]
        node: ['14']
      
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
        pushd swift_browser_ui_frontend
        npm install
        npm run build
    - name: Install firefox driver
      run: |
        wget https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
        tar -xvzf geckodriver-v0.27.0-linux64.tar.gz
        rm geckodriver-v0.27.0-linux64.tar.gz
        chmod +x geckodriver
        sudo cp geckodriver /usr/local/bin/
        geckodriver --version
        sudo apt-get update
        sudo apt-get install firefox -y
    - name: Test UI in Firefox
      run: tox -e firefox
