name: PNPM auto update packages

on: 
  pull_request:
    branches: [devel]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18']
    name: pnpm packages update
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
          cache-dependency-path: swift_browser_ui_frontend/pnpm-lock.yaml
      - name: Install dependencies
        run: |
          pushd swift_browser_ui_frontend
          pnpm update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update pnpm packages
          title: pnpm package updates
          body: |
            Automated PR with PNPM updates

            Close and re-open this PR for the checks to run.
          branch: update/pnpm-updates
          base: feature/pnpm-auto-update
