name: Publish Docker image

on:
  release:
    types: [published]
  push:
    branches: [master, devel]

jobs:
  push_to_registry:
    name: Push swift-x-account-sharing Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Build the tagged Docker image
        if:  ${{ steps.vars.outputs.tag != '/master' }}
        run: docker build . --file Dockerfile --tag cscfi/swift-x-account-sharing:${{steps.vars.outputs.tag}}
      - name: Push the tagged Docker image
        if:  ${{ steps.vars.outputs.tag != '/master' }}
        run: docker push cscfi/swift-x-account-sharing:${{steps.vars.outputs.tag}}
      - name: Build the latest Docker image
        if:  ${{ steps.vars.outputs.tag == '/master' }}
        run: docker build . --file Dockerfile --tag cscfi/swift-x-account-sharing:latest
      - name: Push the latest Docker image
        if:  ${{ steps.vars.outputs.tag == '/master' }}
        run: docker push cscfi/swift-x-account-sharing:latest
      - name: Build the stage Docker image
        if:  ${{ steps.vars.outputs.tag == '/devel' }}
        run: docker build . --file Dockerfile --tag cscfi/swift-x-account-sharing:stage
      - name: Push the stage Docker image
        if:  ${{ steps.vars.outputs.tag == '/devel' }}
        run: docker push cscfi/swift-x-account-sharing:stage
