name: Spelling Errors Check

on: [push]

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
      
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@0.25.0
      name: Spellcheck
      with:
        config_path: .github/config/.spellcheck.yml
