name: Spelling Errors Check

on:
  pull_request:

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: rojopolis/spellcheck-github-actions@0.38.0
        name: Spellcheck
        with:
          config_path: .pyspelling.yml
