name: Vue.js Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16"]
    name: Jest unit tests
    steps:
      - uses: actions/checkout@v3
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies and run tests
        run: |
          pushd swift_browser_ui_frontend
          npm install
          npm test
